import Head from 'next/head'
import { Inter } from 'next/font/google'
import About from '@/components/about'
import Screen from '@/components/multiple-screen'
import { useRef } from 'react'
import Stat from '@/components/statistic'
import Newsletter from '@/components/newsletter'
import MobileScreen from '@/components/mobileScreen'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const screenRef = useRef(null);

  const handleScroll = () => {
    if (screenRef.current) {
      screenRef.current.scrollTop = 0;
    }
  };

  return (
    <>
      <Head>
        <title>WashMe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="desktop">
        <section id="presentation">
          <About
          description="Première plateforme de blanchisserie de particulier à particulier<br/>
          Découvrez comment Washme peut vous aider à optimiser votre emploi du temps et à arrondir vos fins de mois grâce à une solution innovante et éco-responsable."
          />
        </section>
        <section id="screen">
          <Screen ref={screenRef} />
        </section>
        <section id="statistic">
          <Stat
          stat="23 214"
          description="Le nombre d'heures économisées par nos utilisateurs dans une vie"
          /><hr></hr>
          <Stat
          stat="31.8"
          description="Le nombre de mois économisées par nos utilisateurs dans une vie"
          /><hr></hr>
          <Stat
          stat="2.7"
          description="Le nombre d'années économisées par nos utilisateurs dans une vie"
          />
        </section>
        <section id='newsletter'>
          <Newsletter/>
        </section>
      </main>
      <main id="mobile">
        <section id="presentation">
            <About
            description="Première plateforme de blanchisserie de particulier à particulier"
            />
        </section>
        <MobileScreen/>
        <section id='newsletter'>
          <Newsletter/>
        </section>
      </main>
    </>
  )
}
